import {createContext,useContext,useEffect,useMemo,useState,type ReactNode} from 'react'; import type {Product} from '../types'; import {fallbackProducts} from '../data/fallback'; import {api} from '../services/api';
export type CartItem=Product&{quantity:number;size:string};
type Ctx={products:Product[];wishlist:string[];cart:CartItem[];toggleWishlist:(id:string)=>void;addToCart:(p:Product,size?:string)=>void;removeFromCart:(id:string,size:string)=>void;changeQty:(id:string,size:string,d:number)=>void;clearCart:()=>void;token:string|null;setToken:(t:string|null)=>void};
const Store=createContext<Ctx|null>(null); const read=<T,>(k:string,d:T):T=>{try{return JSON.parse(localStorage.getItem(k)||'') as T}catch{return d}};
export function StoreProvider({children}:{children:ReactNode}){const [products,setProducts]=useState<Product[]>(fallbackProducts);const [wishlist,setWishlist]=useState<string[]>(()=>read('atelier-wishlist',[]));const [cart,setCart]=useState<CartItem[]>(()=>read('atelier-cart',[]));const [token,setTokenState]=useState<string|null>(()=>localStorage.getItem('atelier-token'));
useEffect(()=>{api.products().then(x=>setProducts(x.products.length?x.products:fallbackProducts)).catch(()=>setProducts(fallbackProducts))},[]);useEffect(()=>localStorage.setItem('atelier-wishlist',JSON.stringify(wishlist)),[wishlist]);useEffect(()=>localStorage.setItem('atelier-cart',JSON.stringify(cart)),[cart]);
useEffect(()=>{if(token){api.syncWishlist(token,wishlist).catch(()=>{});api.syncCart(token,cart).catch(()=>{})}},[token]);
const toggleWishlist=(id:string)=>setWishlist(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);const addToCart=(p:Product,size='M')=>setCart(v=>{const e=v.find(i=>i.id===p.id&&i.size===size);return e?v.map(i=>i.id===p.id&&i.size===size?{...i,quantity:i.quantity+1}:i):[...v,{...p,size,quantity:1}]});const removeFromCart=(id:string,size:string)=>setCart(v=>v.filter(i=>!(i.id===id&&i.size===size)));const changeQty=(id:string,size:string,d:number)=>setCart(v=>v.map(i=>i.id===id&&i.size===size?{...i,quantity:Math.max(1,i.quantity+d)}:i));const clearCart=()=>setCart([]);const setToken=(t:string|null)=>{setTokenState(t);if(t)localStorage.setItem('atelier-token',t);else localStorage.removeItem('atelier-token')};
return <Store.Provider value={{products,wishlist,cart,toggleWishlist,addToCart,removeFromCart,changeQty,clearCart,token,setToken}}>{children}</Store.Provider>}
export function useStore(){const v=useContext(Store);if(!v)throw new Error('useStore must be used inside StoreProvider');return v}
