import {useEffect,useState} from 'react';
import {Navigate} from 'react-router-dom';
import {PackagePlus,Trash2,Save,RefreshCw,LayoutDashboard} from 'lucide-react';
import {api} from '../services/api';
import {useStore} from '../context/StoreContext';
import type {Product} from '../types';
const blank:Partial<Product>&{stock?:number;description?:string}={name:'',category:'Tops',price:0,image:'',sizes:['S','M','L','XL'],colors:['Black'],stock:10,occasions:['casual'],styles:['minimal'],minTemp:18,maxTemp:35,fabric:'cotton',description:''};
export default function Admin(){const{token}=useStore();const[user]=useState(()=>{try{return JSON.parse(localStorage.getItem('atelier-user')||'null')}catch{return null}});const[products,setProducts]=useState<any[]>([]);const[form,setForm]=useState<any>(blank);const[editing,setEditing]=useState<string|null>(null);const[stats,setStats]=useState<any>({});const[message,setMessage]=useState('');if(!token||user?.role!=='admin')return <Navigate to="/account" replace/>;
 const load=async()=>{try{const [p,s]=await Promise.all([api.adminProducts(token),api.adminStats(token)]);setProducts(p.products);setStats(s)}catch(e:any){setMessage(e.message)}};useEffect(()=>{load()},[token]);
 const save=async()=>{try{editing?await api.updateProduct(token,editing,form):await api.createProduct(token,form);setMessage(editing?'Product updated.':'Product added.');setForm({...blank});setEditing(null);load()}catch(e:any){setMessage(e.message)}};
 const edit=(p:any)=>{setEditing(p.id);setForm(p);window.scrollTo({top:0,behavior:'smooth'})}; const remove=async(id:string)=>{if(!confirm('Delete this product?'))return;await api.deleteProduct(token,id);load()};
 return <main className="shell adminPage"><div className="adminHero"><div><p className="eyebrow">ATELIER/AI ADMIN</p><h1>Control the store.</h1><p>Add pieces, manage inventory and keep the catalog ready for the stylist.</p></div><LayoutDashboard size={38}/></div><div className="adminStats"><div><b>{stats.products??products.length}</b><span>Products</span></div><div><b>{stats.active??0}</b><span>Active</span></div><div><b>{stats.lowStock??0}</b><span>Low stock</span></div></div><section className="adminEditor"><div className="adminTitle"><h2>{editing?'Edit product':'Add a product'}</h2><button className="ghost" onClick={()=>{setEditing(null);setForm({...blank})}}><RefreshCw size={15}/> Reset</button></div><div className="adminForm">{['name','category','price','image','stock','fabric','description'].map(k=><label key={k}>{k}<input value={form[k]??''} onChange={e=>setForm({...form,[k]:k==='price'||k==='stock'?Number(e.target.value):e.target.value})}/></label>)}<label>Sizes<input value={(form.sizes||[]).join(', ')} onChange={e=>setForm({...form,sizes:e.target.value.split(',').map((x:string)=>x.trim()).filter(Boolean)})}/></label><label>Colors<input value={(form.colors||[]).join(', ')} onChange={e=>setForm({...form,colors:e.target.value.split(',').map((x:string)=>x.trim()).filter(Boolean)})}/></label><label>Occasions<input value={(form.occasions||[]).join(', ')} onChange={e=>setForm({...form,occasions:e.target.value.toLowerCase().split(',').map((x:string)=>x.trim()).filter(Boolean)})}/></label><label>Styles<input value={(form.styles||[]).join(', ')} onChange={e=>setForm({...form,styles:e.target.value.toLowerCase().split(',').map((x:string)=>x.trim()).filter(Boolean)})}/></label></div><button className="primary" onClick={save}>{editing?<Save size={16}/>:<PackagePlus size={16}/>} {editing?'Save changes':'Add product'}</button>{message&&<p className="adminMessage">{message}</p>}</section><section className="adminTable"><h2>Catalog</h2>{products.map(p=><div className="adminRow" key={p.id}><img src={p.image}/><div><b>{p.name}</b><span>{p.category} · ₹{p.price?.toLocaleString('en-IN')} · {p.stock??0} in stock</span></div><button className="ghost" onClick={()=>edit(p)}>Edit</button><button className="danger" onClick={()=>remove(p.id)}><Trash2 size={15}/></button></div>)}</section></main>}
